import { WidgetConfig } from '@/types/widgets/widgetConfig';

// Auto-discovery system that finds all widget configs dynamically
// This uses a naming convention to automatically discover widgets

// Define the widget discovery pattern
// All folders ending with 'Widget' are considered widget folders
const WIDGET_FOLDER_PATTERN = /Widget$/;

// Auto-generated widget folders list
// This list is automatically generated by the build script
// To add a new widget:
// 1. Create a folder ending with 'Widget' (e.g., 'NewFeatureWidget')
// 2. Add a widgetConfig.ts file in that folder
// 3. Run: npm run generate-widget-list
// 4. The widget will be automatically discovered and loaded
const WIDGET_FOLDERS = [
  'AsciiDistributionWidget',
  'ChiSquaredWidget',
  'ExpectedBinOccupancyWidget',
  'FrequencyAnalysisWidget',
  'FrequencyStdDevWidget',
  'IndexOfCoincidenceWidget',
  'KolmogrovSmirnovWidget',
  'ShannonEntropyWidget',
];

// Registry that auto-discovers all widget configs dynamically
const WIDGET_REGISTRY = new Map<string, WidgetConfig>();

// Initialize the registry synchronously to avoid async issues
function initializeWidgetRegistry(): void {
  // Import all widget configs synchronously
  const configs = [
    require('./AsciiDistributionWidget/widgetConfig').default,
    require('./ChiSquaredWidget/widgetConfig').default,
    require('./ExpectedBinOccupancyWidget/widgetConfig').default,
    require('./FrequencyAnalysisWidget/widgetConfig').default,
    require('./FrequencyStdDevWidget/widgetConfig').default,
    require('./IndexOfCoincidenceWidget/widgetConfig').default,
    require('./KolmogrovSmirnovWidget/widgetConfig').default,
    require('./ShannonEntropyWidget/widgetConfig').default,
  ];

  configs.forEach((config) => {
    if (config && config.id) {
      WIDGET_REGISTRY.set(config.id, config);
      console.log(`✅ Auto-discovered widget: ${config.name} (${config.id})`);
    } else {
      console.warn(`⚠️ Invalid widget config: missing id`);
    }
  });

  console.log(`🎯 Widget registry initialized with ${WIDGET_REGISTRY.size} widgets`);
}

// Initialize the registry immediately
initializeWidgetRegistry();

// Helper functions for accessing widget configurations
export function getWidgetConfig(widgetId: string): WidgetConfig | undefined {
  return WIDGET_REGISTRY.get(widgetId);
}

export function getAllWidgetConfigs(): WidgetConfig[] {
  return Array.from(WIDGET_REGISTRY.values());
}

export function getSettingsKeys(): string[] {
  return getAllWidgetConfigs().map(config => config.settingsKey);
}

export function getDefaultSettings(): Record<string, any> {
  const defaults: Record<string, any> = {};
  getAllWidgetConfigs().forEach(config => {
    defaults[config.id] = config.defaultSettings;
  });
  return defaults;
}

export function getWidgetIds(): string[] {
  return Array.from(WIDGET_REGISTRY.keys());
}

export function validateWidgetSettings(settings: Record<string, any>): boolean {
  let isValid = true;

  Object.entries(settings).forEach(([widgetId, widgetSettings]) => {
    const config = WIDGET_REGISTRY.get(widgetId);
    if (config?.validator && !config.validator(widgetSettings)) {
      console.error(`Invalid settings for widget ${widgetId}:`, widgetSettings);
      isValid = false;
    }
  });

  return isValid;
}

// Export the registry for direct access if needed
export { WIDGET_REGISTRY };
