#!/usr/bin/env node

/**
 * Build script to auto-generate the widget folders list
 * Run this script to update the widget registry with newly discovered widgets
 */

const fs = require('fs');
const path = require('path');

// Path to the widgets directory
const WIDGETS_DIR = path.join(__dirname, '../components/widgets');
const REGISTRY_FILE = path.join(__dirname, '../components/widgets/widgetRegistry.ts');

/**
 * Discover all widget folders
 */
function discoverWidgetFolders() {
  const results = [];

  try {
    const items = fs.readdirSync(WIDGETS_DIR);

    for (const item of items) {
      const itemPath = path.join(WIDGETS_DIR, item);
      const stat = fs.statSync(itemPath);

      if (stat.isDirectory() && item.endsWith('Widget')) {
        const configPath = path.join(itemPath, 'widgetConfig.ts');
        const hasConfig = fs.existsSync(configPath);

        if (hasConfig) {
          results.push(item);
        } else {
          console.warn(`⚠️ Widget folder '${item}' is missing widgetConfig.ts`);
        }
      }
    }
  } catch (error) {
    console.error('❌ Error discovering widget folders:', error);
    process.exit(1);
  }

  return results;
}

/**
 * Generate the widget registry content
 */
function generateRegistryContent(widgetFolders) {
  const folderList = widgetFolders.map(folder => `  '${folder}'`).join(',\n');

  return `import { WidgetConfig } from '@/types/widgets/widgetConfig';

// Auto-discovery system that finds all widget configs dynamically
// This uses a naming convention to automatically discover widgets

// Define the widget discovery pattern
// All folders ending with 'Widget' are considered widget folders
const WIDGET_FOLDER_PATTERN = /Widget$/;

// Auto-generated widget folders list
// This list is automatically generated by the build script
// To add a new widget:
// 1. Create a folder ending with 'Widget' (e.g., 'NewFeatureWidget')
// 2. Add a widgetConfig.ts file in that folder
// 3. Run: npm run generate-widget-list
// 4. The widget will be automatically discovered and loaded
const WIDGET_FOLDERS = [
${folderList},
];

// Registry that auto-discovers all widget configs dynamically
const WIDGET_REGISTRY = new Map<string, WidgetConfig>();

// Initialize the registry with all available widget configs
async function initializeWidgetRegistry(): Promise<void> {
  const configPromises = WIDGET_FOLDERS.map(async (folderName) => {
    try {
      // Dynamic import based on folder name
      const module = await import(\`./\${folderName}/widgetConfig\`);
      const config = module.default;

      if (config && config.id) {
        WIDGET_REGISTRY.set(config.id, config);
        console.log(\`✅ Auto-discovered widget: \${config.name} (\${config.id})\`);
      } else {
        console.warn(\`⚠️ Invalid widget config in \${folderName}: missing id\`);
      }
    } catch (error) {
      console.warn(\`❌ Failed to load widget config from \${folderName}:\`, error);
    }
  });

  await Promise.all(configPromises);
  console.log(\`🎯 Widget registry initialized with \${WIDGET_REGISTRY.size} widgets\`);
}

// Initialize the registry immediately
initializeWidgetRegistry().catch(error => {
  console.error('💥 Failed to initialize widget registry:', error);
});

// Helper functions for accessing widget configurations
export function getWidgetConfig(widgetId: string): WidgetConfig | undefined {
  return WIDGET_REGISTRY.get(widgetId);
}

export function getAllWidgetConfigs(): WidgetConfig[] {
  return Array.from(WIDGET_REGISTRY.values());
}

export function getSettingsKeys(): string[] {
  return getAllWidgetConfigs().map(config => config.settingsKey);
}

export function getDefaultSettings(): Record<string, any> {
  const defaults: Record<string, any> = {};
  getAllWidgetConfigs().forEach(config => {
    defaults[config.id] = config.defaultSettings;
  });
  return defaults;
}

export function getWidgetIds(): string[] {
  return Array.from(WIDGET_REGISTRY.keys());
}

export function validateWidgetSettings(settings: Record<string, any>): boolean {
  let isValid = true;

  Object.entries(settings).forEach(([widgetId, widgetSettings]) => {
    const config = WIDGET_REGISTRY.get(widgetId);
    if (config?.validator && !config.validator(widgetSettings)) {
      console.error(\`Invalid settings for widget \${widgetId}:\`, widgetSettings);
      isValid = false;
    }
  });

  return isValid;
}

// Export the registry for direct access if needed
export { WIDGET_REGISTRY };
`;
}

/**
 * Main function
 */
function main() {
  console.log('🔍 Discovering widget folders...');

  const widgetFolders = discoverWidgetFolders();

  if (widgetFolders.length === 0) {
    console.log('❌ No widget folders found');
    process.exit(1);
  }

  console.log(`✅ Found ${widgetFolders.length} widget folders:`);
  widgetFolders.forEach(folder => console.log(`  - ${folder}`));

  console.log('📝 Generating widget registry...');
  const registryContent = generateRegistryContent(widgetFolders);

  try {
    fs.writeFileSync(REGISTRY_FILE, registryContent);
    console.log('✅ Widget registry generated successfully!');
    console.log(`📁 Updated: ${REGISTRY_FILE}`);
  } catch (error) {
    console.error('❌ Failed to write registry file:', error);
    process.exit(1);
  }
}

// Run the script
if (require.main === module) {
  main();
}